### ISSUE TITLE
Adaptive Lighting Sleep Mode dims light during day

### ISSUE THREAD

**Issue by cpuks** [basnijholt/adaptive-lighting#1025]
I've set up latest adaptive-lightning for my lights - mixed zigbee (z2m), yeelight and I found out that no matter what I change in light configuration when I turn on Adaptive Lighting Sleep Mode it works immediately even in the middle of the day but as I understand that should be only effective during nighttime (after sunset before sunrise).
Tried different sunset / sunrise options -> None, certain time periods like rise 07:00:00 and set 23:00:00 - no luck, tried transition_until_sleep on/off, but that didn't change anything either. All other options like brightness and temperature work fine except sleep mode.
Anyone has a solution to this, as for now I've got an automation that turns on sleep mode at certain time and off in the morning - it shouldn't be like that?

**Comment by SFA17SCM58D** [comment]
I am also seeing the same issue

**Comment by basnijholt** [comment]
The sleep mode is on when the switch is on regardless of the time of the day. This is by design. This is explained in the read me. Please tell me which part is unclear?

**Comment by AeliusSaionji** [comment]
The confusing factor (for me) is the fact that "transition to sleep" has no effect when turning the light on after sunset, and there appears to be no way to enter sleep mode once you've passed sunset.

In effect, the configured sleep mode is not working.
There's a prominent sleep mode toggle switch, next to other _transitional_ option switches, so that sticks out as the "obvious" solution: there's a toggle for "_transition_ to sleep mode" you have to enable!
... until you realize that it's now permanently in sleep mode :)

**Comment by cpuks** [comment]
Sorry for delay as I'm this issue owner/creator, but as @AeliusSaionji said - it's unclear how this works.
Sometimes I need to play with settings to get proper night light especially with many different bulbs / rooms and beside toggle switch there's no other way how to trigger AL to test things. Manual sunrise/sunset does not work at all with or without transition_to_sleep_mode - for example I set manual sunrise to 08:00:00 and manual sunset to 08:45:00 and nothing happens, same goes for night time when those times are taken from location.
For now I have automation that triggers sleep mode switch for all the lights.
