### ISSUE TITLE
Treat lights in a scene as manually controlled

### ISSUE THREAD

**Issue by blueshiftlabs** [basnijholt/adaptive-lighting#12]
Add support to treat a light as manually controlled if it comes on via a scene. Ideally, this would be configurable to trigger on any scene, or only scenes from a designated list.

You can tell if a light was activated via scene by listening for the `call_service` event for `scene.turn_on`. The context for that event will be the same as the context for any later `light.turn_on` calls the scene triggers.

**Comment by basnijholt** [comment]
This is a great idea, I will try to implement this when I make the time.

**Comment by mikkelzzz3** [comment]
Yes, this would be perfect! I have scenes set up with automation for Plex. White color when watching movies, dim when playing, bit brighter when pausing etc.

But what happens is adaptive lighting keeps messing with the color of the bulbs.

@basnijholt I sure do hope you will find time for it at some point :)

**Comment by paviro** [comment]
If added please make this optional :) I use scenes in https://github.com/benleb/ad-automoli to enable different lights depending on the time of day. They only turn the lights on and don't have any brightness / color information so that adaptive-lighting can then change it depending on the time. If I want a scene to really stick I just add the adaptive-lighting switch to the scene and disable it temporarily. 

Having an option for this is nice of course or as @blueshiftlabs noted maybe a list of scenes where it shouldn't adjust the settings. I also have scenes where I use colors and disable the color part of adaptive-lighting while they are active so that the brightness still changes but not the Colors.

**Comment by RubenKelevra** [comment]
Hey @blueshiftlabs,

I think this is very similar to the issue https://github.com/basnijholt/adaptive-lighting/issues/132. Can you read it and report back if we can merge these both together somehow?

The question here is, would it be enough for you to just change the light temperature/brightness and the active light bulbs between profiles, or do you need more functionality?

**Comment by RubenKelevra** [comment]
This went stale.

**Comment by martinusje** [comment]
Hi, is there any update on this? 
I can not find a way to enable a scene while the lights are off without AL taking over! Even if I enable manual_control before turning them on from the scene, it still immediately takes over. Is there a way for AL to recognize the lights turning on from a scene and therefore not taking over?

**Comment by turkomano** [comment]
I am facing the same issue, I have to enable scene's once, twice or even thrice for my scene to properly activate. This is due to AL taking over control, although take_over_control is enabled. There should be a way to turn on lights without triggering AL (f.e. an attribute to the light.turn_on service.

**Comment by basnijholt** [comment]
I fixed this yesterday with https://github.com/basnijholt/adaptive-lighting/pull/709.

Please try out 1.19.0 (beta)!
