### ISSUE TITLE
Error after upgrading to Home Assistant core-2021.6.2

### ISSUE THREAD

**Issue by nobes1** [basnijholt/adaptive-lighting#130]
The adaptive lighting integration does not load after the latest update to Home Assistant core-2021.6.2. I've tried removing the integration to reinstall it but I can't locate it to re-install. Has the integration been removed?

**Comment by RubenKelevra** [comment]
Have you tried to remove it via HACS, restart HA and reinstall it via HACS and restart HA?

This should clean it up.

I can confirm that the integration is working with 2021.6.2.

**Comment by nobes1** [comment]
Thanks for the reply. I’ve removed it and restarted home assistant. The integration is no longer showing up but I also can’t seem to find it in HACS to reinstall. I’ve tried a full reboot too.

Any advice appreciated.

________________________________

**Comment by RubenKelevra** [comment]
It isn't listed in HACS by default. You have to add the address of the repo to the list of the custom repositories in the HACS panel:


https://user-images.githubusercontent.com/614929/121225564-ee5bcb00-c889-11eb-933b-485552381681.mp4

(it's already existing in my installation, that's why I get the error)

**Comment by RubenKelevra** [comment]
You're welcome. Please close this ticket :)
