### ISSUE TITLE
Add ability to switch to manual mode for only brightness

### ISSUE THREAD

**Issue by gderber** [basnijholt/adaptive-lighting#166]
First to help understand my configuration, I have set up an adaptive-lighting entity for each light fixture.  This way I can set one fixture to manual while leaving the others alone.

During the day, I like to have the color temperature change the whole day.  Sometimes I like to decrease the brightness level (especially a lamp near my desk).  I still want the color temperature to change.

So the ability to switch brightness control to manual, while leaving the rest of the system running would be helpful.

I'm thinking something along the lines of

if brightness is changed:
  if brightness_only_switch:
    set adaptive_lighting_brightness "off"
else:
  set adaptive_lighting_to_manual: "on"

With the idea being if I manually change the color value it'll turn the whole thing off, while if it's only the brightness I changed it'll only turn off the brightness control.

**Comment by RubenKelevra** [comment]
Hey @gderber,

thanks for your input, I think we have this already on our todo list:

https://github.com/basnijholt/adaptive-lighting/issues/132

If you agree I would like to mark this as a duplicate. If not, please elaborate why this won't cover your usecase :)

**Comment by gderber** [comment]
It might be covered by #132, but I am not certain.

I am not sure how simply turning off the brightness adjustment if I manually adjust the brightness while still leaving the color temperature adjustment active relates to multiple light "modes"

**Comment by woobins** [comment]
I would like this feature as well since we often turn down the brightness while watching a movie but I'd still like the color temp to be adjusted.  I'm not sure that #132 covers this either.

**Comment by michaelcrossland1979** [comment]
It be nice to have the flip where you can set the colors to whatever you like but have you stuff so that the brightens is that only thing that changes not the light tone or color.

**Comment by michaelcrossland1979** [comment]
Well that the thing some lights don't play nice with that at all. like the Govee ones that you can pick up very easily at Lowes stores or even online and they do a great job but they don't play nice with HA as someone had to come up with a 3rd party way to get the lights and other things to they make to be able to be used without the need for Bluetooth that is if your setup would even let you use Bluetooth to begin with. So all I'm asking is for a way to be able to not have to set any color as a thing for those of us that can't go whole hog with are setups.

**Comment by RubenKelevra** [comment]
Hey @michaelcrossland1979,

I don't think I can follow your setup and train of thoughts here fully...

Would you mind creating a new ticket for this?

The exact type devices itself doesn't matter much, it's just important how HA "sees" it.

So just download the diagnostic data for the device and add it to the new ticket:

![Screenshot_2023-05-31-11-30-33-308_io homeassistant companion android](https://github.com/basnijholt/adaptive-lighting/assets/614929/425f1eea-91ca-43ed-b57a-e93872e930fa)

**Comment by michaelcrossland1979** [comment]
Well I'll just have to find some other way to deal with it my self. Because in the case of the 2 lights that I don't want it to change colors on those are outside lights and if left with the warmer colors you can guess what happens not to long after sun goes down all the bugs come right for those lights unless they are left in a very dark red color. But otherwise have no problems with it for the  main house lights.

**Comment by michaelcrossland1979** [comment]
See there is a very good use case for a advacted setting like that where the user can disable the color part but leave the dimming part alone. That or say when my plex server gets done playing something and I would just like my lights that where dimmed using webhoocks to stay that nice deep red but to just come back up to the bightens of what the rest are set at. Because don't know about you but have you sat in almost dark for 2 or 3 hours with just the TV and some low lights running at dark red and then have pop right up to a warm whitgh light that will blind you? I know I have and it's no fun what so ever.
