### ISSUE TITLE
Color adapt without brightness adjust

### ISSUE THREAD

**Issue by ikrEErki** [basnijholt/adaptive-lighting#25]
This is an awesome update coming from circadian. However, I can't figure out how to only adjust color, not brightness? Is this possible? If not, please consider this a feature request :)

**Comment by basnijholt** [comment]
https://github.com/basnijholt/adaptive-lighting/issues/21#issuecomment-714511577

**Comment by basnijholt** [comment]
That is because those options are now switches such that you can automate it.

See the docs here: https://deploy-preview-14877--home-assistant-docs.netlify.app/integrations/adaptive_lighting/

![image](https://user-images.githubusercontent.com/6897215/97105597-617a4d80-16bc-11eb-8391-ec9111db5ee5.png)

**Comment by basnijholt** [comment]
I consider this solved. Please ping me here if this is not the case.
