### ISSUE TITLE
Interaction issue with pyscript?

### ISSUE THREAD

**Issue by GollyJer** [basnijholt/adaptive-lighting#250]
I'm using the latest versions of Home Assistant, Adaptive Lighting, and pyscript.

Everything seems to be working perfectly but I notice an Adaptive Lighting error in my logs.
Details are posted in the pyscript discussion if someone here can shed any light on the issue.
[Interaction with other components?](https://github.com/custom-components/pyscript/discussions/310)

Thanks!

**Comment by th3w1zard1** [comment]
@GollyJer Did you manage to fix this? Otherwise are you getting this with the latest version of adaptive-lighting? What HA Core version are you using?

**Comment by th3w1zard1** [comment]
@GollyJer Sounds great, please keep us posted!

**Comment by th3w1zard1** [comment]
@GollyJer Hey letting you know the 'phantom lights' issue should be fixed by the last release.

**Comment by basnijholt** [comment]
From the discussion you linked (https://github.com/custom-components/pyscript/discussions/310#discussioncomment-2148779) I understand this issue occurred because you are using `area_id`. 

AL didn't support areas at the time, but now they are. 

Therefore I am closing this issue for now. Let me know if you are still having issues and we can reopen.

@GollyJer, BTW the random turning on issues should disappear since 1.18.0 if you set `detect_non_ha_changes: false` (see README).
