### ISSUE TITLE
Proper support for WLED WWA (Cool White, Warm White, Amber) LED-strip

### ISSUE THREAD

**Issue by d-dsn** [basnijholt/adaptive-lighting#252]
WWA led strip has 3 different white channels, "Cool White", "Warm White" and "Amber" instead of "Red", "Green" and "Blue".
Cool White is approximately 6000K, Warm White 3000K and Amber maybe 2000K and those color temperatures map to RGB values (255,0,0), (0,255,0) and (0,0,255). Instead of trying to mix white from all the RGB channels, could these pure color values be mapped to certain Kelvin-values?

**Comment by th3w1zard1** [comment]
A duplicate https://github.com/basnijholt/adaptive-lighting/issues/289 was posted after this issue was slept on. Including in the roadmap.

@d-dsn if you're around, are you able to answer the [question I posted here](https://github.com/basnijholt/adaptive-lighting/issues/289#issuecomment-1481389628) as I'd love to help but I don't have those lights to be able to test this on my end.
