### ISSUE TITLE
take_over_control and groups

### ISSUE THREAD

**Issue by JonathanTroyer** [basnijholt/adaptive-lighting#304]
#### Version information:
1.0.15
Home assistant core 2022.7.2
HACS 1.26.0

#### Description:

`take_over_control` does not respect changes to lights in a group when adapting a group.
E.G. I have light a and b, with group g. If adaptive lighting is set to control g, then changes to a or b (as opposed to g) get overridden at the next interval. If you instead choose to adapt a and b instead of g, then changes to g get overridden. If I try to adapt a, b, and g then both cases of overriding happen.

This plays out most obviously when adapting the auto-generated group for an area. If I adapt light.bedroom, then changes to light.fan get overridden, etc. as described above. However, it is not limited to adapting an area group.

**Comment by th3w1zard1** [comment]
Please post your adaptive-lighting config and your ZHA config. Any config needed to reproduce your issue we need you to share.

**Comment by akmolina28** [comment]
@nathang21 

I found a work-around for this problem that might help. In my case I was using Zigbee groups, which home assistant sees as a totally separate entity. HA has no idea that bulb A and bulb B are part of zigbee group G... it just sees G as a separate light.

There are actually two solutions that work and I'm currently testing to see which is more reliable.

#### Solution 1: Use the ```detect_non_ha_changes``` option:
1. Add the individual light entities to a single Adaptive Lighting entry. Do NOT add the zigbee group.
2. Check the box in the entry for ```detect_non_ha_changes```

Now when you control the lights using the zigbee group, adaptive lighting *should* flag every light in the group as manually controlled. According to the documentation though this isn't full-proof and could cause undesired behavior.

#### Solution 2: Create a separate helper group
1. As in solution 1, add the individual light entities to a single Adaptive Lighting entry. Do NOT add the zigbee group.
2. Add the same lights to a helper group in home assistant.

When you control the lights using the helper group, adaptive lighting will flag all the lights in that group as manually controlled. This gives you a good way to adjust a group of lights as a single entity, but you have an extra dummy entity to deal with. If you have a lot of groups this could get tedious, because every time you change an adaptive lighting group you will also have to update your dummy group to match it.

Neither solution is perfect because adaptive lighting is not using zigbee groups to issue its commands. Issuing individual commands for each light is not optimal and could saturate your zigbee network depending on your setup. In my case both solutions seem to work and I'm currently testing to see which one, if either, is buggier.

**Comment by basnijholt** [comment]
I would recommend using normal, Home Assistant light groups. Zigbee groups, indeed, will not work well.

**Comment by nathang21** [comment]
+1 I use Home Assistant Groups and after the improvements from @th3w1zard1 a couple months ago, it's been working great. Thanks for following up @akmolina28!

**Comment by basnijholt** [comment]
I believe this is a documentation issue.

Unfortunately, there is really nothing one can do to get the lights in a Zigbee group. So use a Home Assistant Light Group instead if you need individual control too.

I have added a **WARNING** here: https://github.com/basnijholt/adaptive-lighting/pull/708
