### ISSUE TITLE
"color_temp_mired" attribute disappeared from switch.adaptive_lighting_ after updating to 1.4.1

### ISSUE THREAD

**Issue by haseat** [basnijholt/adaptive-lighting#403]
#### Version information:
1.4.1

#### Description:
After updating to version 1.4.1 this morning my lights would not turn on anymore. After investigating i found out that the attribute "color_temp_mired" (which i used to turn on my lights for color_temp) did not exist anymore in the adaptive light switch entities, so the light.turn_on would throw an error.

Workaround: use color_temp_kelvin instead

For me it was an easy fix as I'm using a Node-Red subflow to turn on my lights, and I had to implement the change only in one place, but others might not be as lucky.

**Comment by gderber** [comment]
I am definitely not that lucky.

I used mireds to update the state of my hue scenes so that when I used dimmer switch to turn on the lights, they turned on to the correct color temperature.  Unfortunately, hue still needs mireds to update the scene.

**Comment by MizterB** [comment]
@gderber the conversion is pretty simple - see https://github.com/home-assistant/core/blob/3312a041fd0adbc0b6f3e857106f575e75deaa81/homeassistant/util/color.py#L626

I am using your Hue scene sync method and adapted it accordingly.  Our scripts are different, but I did a conversion like this:
```
{% set kelvin = state_attr(adaptive_switch_id, "color_temp_kelvin") if state_attr(adaptive_switch_id, "color_temp_kelvin") is number else int(3670) %}
{% set mired = (1000000 / kelvin)|round(0,'floor') %}
```

**Comment by gderber** [comment]
@MizterB Thank you!  I had no idea how to do the conversion.

Also, thank you for letting me know you are using my scripts I am glad to know they have helped someone.

I am still tweaking them myself. Latest tweak, I now have one rest_command per number of lightbulbs in a scene, then added an input_text for each bulb's id, and an input_text for each scene id.  Then added as a variable in the script something like 'bulb01 = {{ input_text.bulb_name }}'

Makes it a little easier to move a bulb or make other changes without having to hunt down everywhere I used that bulb id.

**Comment by th3w1zard1** [comment]
Anyone who's had this issue, which version were you updating from?

I'd love to add this back in for cross-compatibility.

**Comment by gderber** [comment]
I had to revert back to 1.3.0 to get it working.

I am in the process of implementing a work around. I'd still prefer a built in solution.

**Comment by th3w1zard1** [comment]
I'm still a bit confused where your issue lies. I'm looking at the code from 1.3.0 and comparing to current to see what changed.

Just to confirm: adaptive-lighting is unable to adapt your light because the light uses Mirens over Kelvin?
If that's what I'm understanding, I'm confused why the other posts are suggesting using conversion methods, as there's no way to convert what's in the integration via an automation?

If you could post some more information I'd be happy to integrate backward-compatibility for you in the next upcoming version, as it should be a simple change with pre-existing code.

**Comment by th3w1zard1** [comment]
@gderber also can you confirm your adaptive-lighting 1.3.0 version works on the latest hass core version? If not could you at least tell me which hass core version you're running?

**Comment by th3w1zard1** [comment]
I believe I've identified the problem. [From HASS core source](https://github.com/home-assistant/core/blob/12352b2ce1ca27eb3ecbb54afa2d64e0c10d8d44/homeassistant/components/light/__init__.py#L200):
```
ATTR_COLOR_TEMP = "color_temp"  # Deprecated in HA Core 2022.11
ATTR_KELVIN = "kelvin"  # Deprecated in HA Core 2022.11
ATTR_MIN_MIREDS = "min_mireds"  # Deprecated in HA Core 2022.11
ATTR_MAX_MIREDS = "max_mireds"  # Deprecated in HA Core 2022.11
```

From my understanding, updating HASS core should fix your problem. Regardless I know how much of a pain updating home assistant is and dealing with all the breaking changes, so I'd still like to introduce backwards compatibility here.

**Comment by th3w1zard1** [comment]
Alright I think I understand the problem well enough now, did you just want the `color_temp_mired` attribute back or do your lights simply do not respond to service data containing `color_temp_kelvin`?

**Comment by gderber** [comment]
The problem is, I use hue switches to turn on my lights.

To get the lights to turn on to the correct color temperature I have to update a hue scene periodically using a script with rest_commands and set it to use the current color temp in adaptive lighting.  Hue scenes require the color temp to be defined in mireds.

This attribute was removed with PR #375.

With Home Assistant changing the default color temp to Kelvin, making Kelvin the default for adaptive lighting makes sense.  However, rather than simply making Kelvin the default, the mired attribute was completely removed. 

This attribute was specifically part of adaptive lighting, not related to any Home Assistant source code.

**Comment by th3w1zard1** [comment]
I've added the color_temp_mired back in a future pull request. That part was easy (1 line of code). It'll be exactly the same as it was for backwards compatibility.

Are you also, additionally, saying that your lights won't accept light.turn_on calls with color_temp_kelvin? Because that is a separate larger problem I'd like to escalate (if it's happening).

**Comment by gderber** [comment]
I'm sure the lights would work using lights.turn_on with the right kelvin setting.

I normally use hue switches to turn on my lights for a variety of reasons.

**Comment by th3w1zard1** [comment]
great! I'll move this issue further up the queue.

**Comment by th3w1zard1** [comment]
@gderber I have added your feature request to PR #460, feel free to try it out yourself!

**Comment by gderber** [comment]
@th3w1zard1 Thank you!
