### ISSUE TITLE
All lights are set to the lowest brightness level when turned on, even if they're not in an AL group

### ISSUE THREAD

**Issue by higbyk** [basnijholt/adaptive-lighting#490]
#### Version information:
1.7.0

#### Description:
I updated to v1.7.0 and noticed that the basement lights were turning on to the lowest brightness level. The motion triggered automation that turns them on specifically sets them to the brightest level, so I thought this was odd.

I noticed that this was happening to the living room lights as well, and tested by removing one of the living room lights from the adaptive lighting group that they are all in. This did not fix the issue, even after fully restarting Home Assistant.

What did fix the issue was disabling both adaptive lighting groups.

The version I was on before I upgraded to 1.7.0 was 1.5.0. I am currently testing 1.6.0 and we'll follow up with my results.

**Comment by higbyk** [comment]
I should have mentioned this only happens when turning the lights on. If they are on already, you can adjust the brightness just fine.

That should help narrow down where the issue is!

**Comment by th3w1zard1** [comment]
So just to clarify, you weren't having issues with an older version of adaptive lighting? Which version correctly worked with this issue?

**Comment by higbyk** [comment]
Yes, 1.5.0 worked fine for me.

**Comment by higbyk** [comment]
I just tested and the issue happens in 1.6.0 too.

**Comment by th3w1zard1** [comment]
Your adaptive-lighting config, and any relevant debug logs would be helpful too.

**Comment by jjnj023** [comment]
I actually have the same issue.
I at first thought it was an issue with my network and didn't thought of it could be due to the adaptive lighting.
For me this issue occurs as follows:
When setting the color to a different color then it should be according to the adaptive light integration things go wrong. For example when selecting 4000K, and it should be 2200K. Turn off the lamp. Turn on the lamp again at the highest brightness, the lamp will only go to the lowest brightness while Z2m and HA think the light is set to 100.
This was driving me crazy, I even bought a new zigbee stick since I thought it was related to incompatible hardware. I also tested it on the clean setup.
When disabling adaptive lighting for that lamp, no issue is present. 

What can I do to help? What logs do you need and how do I collect them?

**Comment by jjnj023** [comment]
I added logs to a similar issue: [ #212](https://github.com/basnijholt/adaptive-lighting/issues/212#issuecomment-1497523214)
[home-assistant.log](https://github.com/basnijholt/adaptive-lighting/files/11160935/home-assistant.log)

**Comment by dsantos21** [comment]
Not sure if it's the same thing, but in 1.7.x the sundown and sunset times seems bugged. Setting it manually has solved my case (light adapted too dim instead of normal brightness).

**Comment by basnijholt** [comment]
The original issue by @higbyk is solved (sleep mode switch was on).

@jjnj023, I have looked at your logs, and there must be something else that is setting your brightness to 1. From your logs, I see that Adaptive Lighting is reporting to not be changing the brightness at all.

Anyway, if you are still observing this problem, please open a new issue with a more recent version of AL, the logging is much better and there are fewer bugs.
