### ISSUE TITLE
Migrating from z2m to zha created a strange behavior with lamps not being adjusted

### ISSUE THREAD

**Issue by luisleonardo** [basnijholt/adaptive-lighting#540]
#### Version information:
Adaptive Lightning: 1.9.1
Home Assistant 2023.4.0b6
Supervisor 2023.04.0
Operating System 10.0.rc3
Frontend 20230403.0 - latest
(The issue was already present in the latest stable release)

#### Description:
After migrating from zigbee2mqtt to zha, my Ikea Leptiter lamp has a strange behavior. 

Here is an example of that behavior:
- It's midday and light is off.
- The expected brightness from Adaptive Lightning is 100%
- Light was last used at 28%.
- When turned on (HA service/API call from ESPhome) the lamp brightness will be 28%.
- It is expected that quickly after being turned on, the brightness goes to 100% (this is the behavior with all my other ESPHome/tasmota lamps).
- However, HA will report 100%, but the light isn't changed and keeps at 28%.
- After some time (around 3 to 10 minutes) HA will report the correct brightness (28%).
- Later on (it happened at least once) the light would be set to 100%.

I already removed and recreated the Adaptive Lightning entry for this lamp. Is there any other way to completely remove/clean the component, or is there any other thing that I can try to isolate/understand what can be causing this issue?

**Comment by th3w1zard1** [comment]
I don't see how this is an adaptive lighting bug? Sounds like an issue with ZHA

Why did you swap from z2m? Z2m is supposed to be the superior choice

**Comment by th3w1zard1** [comment]
Could you post debug logs, your adaptive lighting config, light brand and model number

**Comment by th3w1zard1** [comment]
@luisleonardo is this the exact model of bulb you're using? https://www.zigbee2mqtt.io/devices/T1820.html

**Comment by jjnj023** [comment]
I think this is relaties or is a similar issue like:
[#212](https://github.com/basnijholt/adaptive-lighting/issues/212#issuecomment-1497523214)

**Comment by th3w1zard1** [comment]
@luisleonardo 

One possible solution for this issue is to check the settings in the ZHA integration for the Ikea Leptiter lamp. It's possible that the lamp is not reporting its state correctly to Home Assistant, which is causing the Adaptive Lighting component to not function as expected.

To check the settings for the lamp in ZHA, follow these steps:

Go to the "Configuration" tab in Home Assistant.
Click on "Integrations".
Find the ZHA integration for the Ikea Leptiter lamp and click on it.
In the "Device Info" section, make sure that the "Manufacturer" and "Model" fields are correct for the lamp.
In the "Device Configuration" section, check the "Reporting" settings for the lamp. Make sure that the "Brightness" attribute is set to report changes in a timely manner.
If the settings in ZHA are correct, try resetting the lamp and re-pairing it with ZHA. It's possible that there was a communication issue between the lamp and the ZHA integration during the migration from zigbee2mqtt to ZHA.

If resetting the lamp and checking the settings in ZHA does not solve the issue, try removing the Adaptive Lighting entry for the lamp and re-creating it. Make sure to restart Home Assistant after removing the entry to ensure that all settings are properly cleared.

If none of these solutions work, it may be necessary to contact the ZHA community or Ikea customer support for further assistance.

**Comment by basnijholt** [comment]
Thanks for your help here @th3w1zard1. This issue seems unrelated to problems in AL and also it has gone stale. Therefore, I’ll close it now. 

@luisleonardo I can re-open if you feel like it.
