### ISSUE TITLE
Adapt Lights before fading up? 

### ISSUE THREAD

**Issue by b3nnyk22** [basnijholt/adaptive-lighting#585]
Hey all

Just wondering if someone has worked out an elegant solution to what I'm trying to achieve. 

As it stands, all of my "Main Lights" have a 5 second fade on and off from their respective automations in HA. I also have the "Initial Transition" for this set of lights in AL set to 5 as it seems if I have this set to 0 it will override the Transition time set by the HA Automation. 

The problem is if I'm turning on a light say late at night and its last setting was day time, it will come on at full whack and in the wrong colour temp before eventually fading as AL takes over. I'm trying to work out a way to have AL have the light adapted before I fade in the brightness so I don't see that ugly transition. 

Any ideas? 

Cheers.

**Comment by benblazak** [comment]
i'm working on a similar problem with my lights. quick search through old issues led me to this: https://github.com/basnijholt/adaptive-lighting/issues/391#issuecomment-1336287078 (another helpful idea a few posts down from that one too, depending on setup). too late to try it myself, but leaving this here since i found your issue first.

**Comment by th3w1zard1** [comment]
> Hey all
> 
> Just wondering if someone has worked out an elegant solution to what I'm trying to achieve.
> 
> As it stands, all of my "Main Lights" have a 5 second fade on and off from their respective automations in HA. I also have the "Initial Transition" for this set of lights in AL set to 5 as it seems if I have this set to 0 it will override the Transition time set by the HA Automation.

This should be impossible because of this code right here:
```
        # Check transition == 0 to fix #378
        if ATTR_TRANSITION in features and transition > 0:
            service_data[ATTR_TRANSITION] = transition
```
This tells me that you're probably not running the latest Adaptive Lighting version. Please update to fix that problem, as setting transition to 0 is indeed how you tell AL to not use transitions.

> The problem is if I'm turning on a light say late at night and its last setting was day time, it will come on at full whack and in the wrong colour temp before eventually fading as AL takes over. I'm trying to work out a way to have AL have the light adapted before I fade in the brightness so I don't see that ugly transition.

This is a highly requested feature that's being voted on in the V2 Roadmap currently. No easy solutions for implementing it have been discovered, but also iirc nobody's really looked into this either.

**Comment by basnijholt** [comment]
Instead of calling light.turn_on you could call adaptive_lighthing.apply to turn on the lights and avoid the blaring lights at night 😄

**Comment by protyposis** [comment]
This is even worse with `separate_turn_on_commands` enabled because it first adapts color, then brightness. I suggested a simple improvement for this in #588 and a way to adapt before fading up in #594 which works with `light.turn_on`.

**Comment by b3nnyk22** [comment]
> This should be impossible because of this code right here:
> 
> ```
>         # Check transition == 0 to fix #378
>         if ATTR_TRANSITION in features and transition > 0:
>             service_data[ATTR_TRANSITION] = transition
> ```
> 
> This tells me that you're probably not running the latest Adaptive Lighting version. Please update to fix that problem, as setting transition to 0 is indeed how you tell AL to not use transitions.
> 

I'm on the latest version of both AL and HA. This behaviour doesn't seem to be correct. Even if I set Initial Transitions to 0 it will ignore Transition Times from HA and snap on.

**Comment by b3nnyk22** [comment]
> Instead of calling light.turn_on you could call adaptive_lighthing.apply to turn on the lights and avoid the blaring lights at night 😄

Even if I use this call I still get the transition from the lights previous state transitioning to the adapted state. Or if I use an Initial Transition time of 0 it snaps which is just as ugly.

**Comment by sam-ward** [comment]
I use the following script I created to solve the problem for me.

```light_toggle:
  alias: light toggle
  fields:
    light:
      description: "The light to toggle"
      example: "light.kitchen"
  sequence:
    - service: light.toggle
      data_template:
        entity_id: "{{ light }}"
        brightness_pct: "{{states('sensor.adaptive_light_brightness') | float(100)}}"
        kelvin: "{{state_attr('switch.adaptive_lighting_main_lights','color_temp_kelvin') | int(4000)}}"
```

In my case, I was trying to solve 2 problems. One, I have some lights that are turned on via either the HA dashboard or via zigbee buttons, and I was getting the same behavior as you with the lights coming on at the wrong brightness and color temp. And secondly when I have visitors around I disable the dimming (by turning off the switch.adaptive_lighting_adapt_brightness) and will have all lights at full brightness.

I don't use it, but you could easily add a transition time to the light.toggle service call in the script. And adjust the default color temp (the int(4000)) to your preferred color temp.

The only downside of using the script is that you need to make sure wherever/however you toggle the light calls the script rather than the system light.toggle.

**Comment by basnijholt** [comment]
This feature has been implemented by @protyposis for single lights for now. Thanks again! 😄🤗

I’ll close this issue.
