### ISSUE TITLE
Redundant adaptation commands not always skipped

### ISSUE THREAD

**Issue by protyposis** [basnijholt/adaptive-lighting#589]
This bug has been identified in the discussion of #588. This block in `_adapt_light` is supposed to skip adaptation commands if the current state of a light already equals a desired state (called `service_data`):
https://github.com/basnijholt/adaptive-lighting/blob/9caf64509349958a340f8cef9207fdb0ea35dbef/custom_components/adaptive_lighting/switch.py#L1176-L1186

Unfortunately, this does not always work and can be reproduced by
1. turning on a light,
2. awaiting adaptation,
3. turning off the light,
4. turning the light back on and noticing (e.g. in Z2M logs) that an adjustment command is sent even though the light is already in the desired state (since it was just adapted in step 2).

I can't post meaningful AL logs, since this issue is only noticeable through the absence of the `Cancelling adapt to light` log messages that signal that an adaptation is skipped. In this example, adding a log for `last_service_data` to the block cited above would print `None`. There are more situations in which it happens, and looking at the implementation, the issues seem to be:
- `last_service_data` is only updated by `_adapt_light()`, hence only by adaptation commands from AL
- `last_service_data` is deleted by `reset()`, e.g., when lights are turned off, the configuration is updated, or manual control is changed
- the comparison includes the transition time

In summary, every initial turn-on of a light, and every turn-on call (e.g., to adjust unrelated state) after a regular adaptation command (which sets the transition to an unusual duration, e.g., the default 45 seconds) potentially lead to unnecessary adaptation commands. It happens because the state isn't tracked over the complete lifetime of the lights, and transitions times interfere with state comparisons. 

This might seem like a minor issue, but unnecessary messages in an active Zigbee network can negatively affect it, and also some lights do not handle multiple parallel messages very nicely, resulting in a suboptimal user experience. For example, transitions of Tradfri lights might get jittery or skipped, or the lights even end up in an invalid state (on, but reported off). It gets twice as worse with `separate_turn_on_commands` enabled.

As a solution, I think that the `last_service_data` should be updated by any changes, no matter if from AL or from elsewhere. What's important is that we know the current state of a light to be able to decide whether an adaptation command is necessary, and that's independent of who set it. This could be done in `state_changed_event_listener`. Also, it should never be deleted, because the lights always have a state. With `separate_turn_on_commands` enabled, it should only send the subset of command that actually changes state (e.g., skip the brightness command but send the color command). I implemented a proof of concept and it works nicely.

**Comment by th3w1zard1** [comment]
The only times that a light will be adapted to the same values as the last_service_data are in the following situations:
1. When the `force` argument is `true` which happens for various events such as a user manually turning off and on their light, flipping the adaptive switch in the UI, calling `adaptive_lighting.apply`, etc.
2. `reset()` is only called when lights are turned off or when manual control is disabled(?)
3. When the transitions differ

This was a relatively new feature we added in a recent release and as transitions do not differ very often it wasn't worth fixing. We were originally trying to quickly put out a major hotfix for the accursed 1.10.0 bug, which caused this feature to sneak its way in. Actually, I believe there's still a PR in progress that is awaiting review to include the transition check.

You need to stabilize your configuration elsewhere.  The last_service_data check was never added to prevent any and all light.turn_on commands, it was supposed to be a simple performance improvement. The short is your bulbs should be able to handle a simple light.turn_on command a few times a minute and you shouldn't need to be relying on this check as heavily as you seem to be. With that said we need to look at your configuration to find the core problem.

I do remember a few years back when I set up adaptive lighting initially that I would get z2m spam, but how I fixed it is long since forgotten. It wasn't even caused by AL; just exacerbated. I believe I modified my z2m configuration and never had the problem again. You can verify this problem with these resources: https://github.com/basnijholt/adaptive-lighting#spider_web-zigbee-z-wave-and-other-mesh-networks and https://github.com/basnijholt/adaptive-lighting/discussions/506 

I realize you question the validity of your AL logs but please know that I understand how difficult it is to provide them. Sometimes there's a bug so sinister and sneaky you just can never capture it at the right time (see #448). But your logs and config do help us try to reproduce the issues.  I personally own the tradfri bulbs and would like to find out why you're experiencing these issues that I am not. I suspect it's a Zigbee configuration setting we've overlooked.

You could try increasing the adaptive-lighting `interval` or setting your `transition` to the same as the `initial transition`. Alternatively, you perhaps might want to try the Adaptive-Lighting Edge version which includes the transition check. You can find it as an optional version in your HACS.

**Comment by protyposis** [comment]
I'm sorry if I wasn't clear enough. I don't care about a few unnecessary commands, what I care about is a smooth user experience. The root of the problem is that my Tradfri bulbs do not apply a fade-in transition to brightness if a command also includes the color temperature. See this example HA service call:

```yaml
service: light.turn_on
data:
  transition: 2
  color_temp: 414
  brightness: 255
```

With this call, which is exactly what AL sends by default after any turn-on command, my bulbs turn on immediately at full brightness, and only the color temperature fades over the transition duration. Maybe that's a Z2M issue, maybe not handled nicely by the bulb's firmware, or maybe even required by the Zigbee standard, but either way, it's out of my hands. To fix this, AL offers the `separate_turn_on_commands` which sends separate commands for brightness and color temperature, but that leads to issue #410 for which I proposed a partial fix in #590.

So how is this related to skipping redundant commands? Whenever commands are skipped, 
- it wouldn't even have the chance to interfere with transitions from regular turn-on commands (e.g. from automations), and
- `separate_turn_on_commands` wouldn't trigger issue #410. 

The issue obviously remains in cases where an adaptation is necessary, but it reduces AL's invasiveness and improves the UX of all the turn-on commands that don't need adaptation. The reduction of network load I mentioned above is a nice side effect which comes for free.

**Comment by th3w1zard1** [comment]
The title of your post is 'Redundant adaptation commands not always skipped' so I tried to answer that specific issue with the details you provided. If you'd like help fixing #410 with `separate_turn_on_commands` I think my reply is still valid. I'm also using the tradfri bulbs and I am not getting these same issues that you are. This tells me that there is something different between our Zigbee setups or our adaptive lighting configs, which is why I provided those details and suggestions in my last [post](https://github.com/basnijholt/adaptive-lighting/issues/589#issuecomment-1543639533).

It seems that you're not referring to the code we talked about that compares the previous values to the current values. Again some logs of Adaptive Lighting specifically calling light.turn_on redundantly would be helpful. Sorry if you find this unhelpful I just don't know how to help without any diagnostics here.

**Comment by protyposis** [comment]
I initially got the wrong impression that the code block cited in my initial post was supposed to skip all unnecessary commands (in this context, an unnecessary command is one that sets a state which is already set). You made it clear that this code wasn't meant to do this and that it only handles one specific case.

So the rest of the text was just me trying to argue for actually implementing a mechanism that skips all redundant commands. The Tradfri bulbs were an example where I know from experience that this yields a worthwhile improvement, but generally this has the potential of positively impacting all setups, e.g., by reducing #410. I also mentioned that I have a working POC, which was a gentle way of suggesting that I could contribute if this idea was accepted.

Your point is that a correct setup should be able to handle all those messages, and an optimization is unnecessary. That's fine, but if anybody else has an opinion on this, I'd still be interested to read it :)
