### ISSUE TITLE
Clear manual control esphome

### ISSUE THREAD

**Issue by broyuken** [basnijholt/adaptive-lighting#60]
I have a smart bulb that uses esphome, and when you turn it off at the light switch and it loses power it doesn’t go to off in HA, it goes to unavailable. If manual control is true, turning it off at the switch doesn’t seem to clear the manual control. Could you add it so if the state goes to off OR unavailable it clears the manual control flag instead of just off?

**Comment by basnijholt** [comment]
Hi @broyuken, please read the discussion here https://github.com/basnijholt/adaptive-lighting/issues/33 where I have a proposed solution.

Perhaps it would work better with the `set_manual_control` service.

Just closing this because that should solve it. Let me know if it doesn't and I will reopen.

**Comment by broyuken** [comment]
The automation work, it’s just an extra piece. It would be nice if there was an option to ignore unavailable -> on or not. Maybe just add it as a checkbox to the configuration page along with the  only once and separate commands checkboxes?

**Comment by basnijholt** [comment]
The reason I didn't implement it like that is (from other issue):
> I purposely chose to not support this option. This is because when a light is manually controlled and briefly becomes unavailable and then back, it will loose its 'manually controlled' status.

> Maybe just add it as a checkbox to the configuration page along with the only once and separate commands checkboxes?

I don't think I will do that now. I think that if this issue is solved with a simple automation, there shouldn't be additional options. Otherwise, we would probably have tens of options for each edge case anyone comes up.

**Comment by broyuken** [comment]
That’s fair, I didn’t think this would be an edge case since it would probably happen to anyone using an esphome bulb. Maybe that in itself is an edge case, I’m not sure lol.

**Comment by basnijholt** [comment]
Let's see if it comes up more often. I'm always open to changing my mind.￼

**Comment by regoras** [comment]
I saw the suggested automation in #33, but was curious if there were a suggestion for a templated version that would address any light. I've got 5 different adaptive lighting groups (4 normally for different areas, 1 for a warmer color temp cap that turns on sometimes) and it would be quite a hassle to set up individual automations for each light or group of lights. Alternatively, if the integration just recognized a transition from unavailable, that would be good also.

**Comment by pluskal** [comment]
I have this issue as well. Not only with ESPHome but also with Tasmota and Tuya-local.

My setup contains one shelly like switch activating multiple ESPHome/Tasmota/Tuya-local lights. Lights transition from `unavailable` into `on` when started. After some time, they may become `unavailable` for a few moments, and so on.

To use `sleep mode`, and/or user overrides per room, I have an adaptive lightning component per room. I am not sure if this issue is really reasonably solvable by templated automation, or is it?

My deployment is 5+ rooms, 100+ lights.   

Related issues: 

- https://github.com/basnijholt/adaptive-lighting/issues/33
- https://github.com/basnijholt/adaptive-lighting/issues/98
- https://github.com/basnijholt/adaptive-lighting/issues/43
