### ISSUE TITLE
Add option to adjust a group instead of the lights in it.

### ISSUE THREAD

**Issue by ironcrafter54** [basnijholt/adaptive-lighting#604]
As Far as I am aware when you have a group in the adaptive lighting component it just looks at the group and control the lights individually within the group instead of controlling the group. The issue with this is that this breaks [lighteneer](https://github.com/fredck/lightener) a new plugin that makes light brightness in group vary. Thanks for having a look at my issue/request.

**Comment by jimmhead** [comment]
I second this, Lightner would be the perfect companion integration for adaptive lighting, but due to this issue the two cannot be used together

**Comment by basnijholt** [comment]
Unfortunately this won’t work because any update to any light in a group changes the state of the group light. There can also be color temperature only logouts mixed with color lights in a group. This means that the group light can never reach the right state and this will mess a lot in Adaptive Lighting. 

Perhaps this issue can be addressed in the other integration?
